___

<a href='http://www.pieriandata.com'> <img src='../Pierian_Data_Logo.png' /></a>
___

# NumPy 

NumPy (or Numpy) is a Linear Algebra Library for Python, the reason it is so important for Data Science with Python is that almost all of the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks.

Numpy is also incredibly fast, as it has bindings to C libraries. For more info on why you would want to use Arrays instead of lists, check out this great [StackOverflow post](http://stackoverflow.com/questions/993984/why-numpy-instead-of-python-lists).

We will only learn the basics of NumPy, to get started we need to install it!

**Check out the [glosasry](https://docs.scipy.org/doc/numpy-1.10.0/glossary.html) for helpful info**

## Installation Instructions

**It is highly recommended you install Python using the Anaconda distribution to make sure all underlying dependencies (such as Linear Algebra libraries) all sync up with the use of a conda install. If you have Anaconda, install NumPy by going to your terminal or command prompt and typing:**
    
    conda install numpy
    
**If you do not have Anaconda and can not install it, please refer to [Numpy's official documentation on various installation instructions.](http://docs.scipy.org/doc/numpy-1.10.1/user/install.html)**

## Using NumPy

Once you've installed NumPy you can import it as a library:

In [1]:
import numpy as np

Numpy has many built-in functions and capabilities. We won't cover them all but instead we will focus on some of the most important aspects of Numpy: vectors,arrays,matrices, and number generation. Let's start by discussing arrays.

# Numpy Arrays

NumPy arrays are the main way we will use Numpy throughout the course. Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d (but you should note a matrix can still have only one row or one column).

Let's begin our introduction by exploring how to create NumPy arrays.

## Creating NumPy Arrays

### From a Python List

We can create an array by directly converting a list or list of lists:

In [3]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [5]:
np.array(my_list)

array([1, 2, 3])

In [7]:
arr = np.array(my_list)
arr

array([1, 2, 3])

In [9]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [10]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
mat = np.array(my_matrix)

In [15]:
mat[0][1]

2

## Built-in Methods

There are lots of built-in ways to generate Arrays

### arange

Return evenly spaced values within a given interval.

In [22]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [18]:
np.arange(-43, 52, 4)

array([-43, -39, -35, -31, -27, -23, -19, -15, -11,  -7,  -3,   1,   5,
         9,  13,  17,  21,  25,  29,  33,  37,  41,  45,  49])

In [20]:
np.arange(0.1, 0.4, 0.01)

array([0.1 , 0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ,
       0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31,
       0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ])

In [23]:
range(0.1, 0.4, 0.01)

TypeError: 'float' object cannot be interpreted as an integer

### zeros and ones

Generate arrays of zeros or ones

**How will these be used later on in the course?**

In [24]:
np.zeros(3)

array([ 0.,  0.,  0.])

In [26]:
np.zeros((5,5))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [27]:
np.ones(3)

array([ 1.,  1.,  1.])

In [24]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [27]:
np.ones((3, 1))  # (rows, columns)

array([[1.],
       [1.],
       [1.]])

In [28]:
rows = 2
columns = 3
np.zeros((rows, columns))

array([[0., 0., 0.],
       [0., 0., 0.]])

### linspace
Return evenly spaced numbers over a specified interval.

**Isn't this used a lot in matplotlib plotting?**

In [29]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [30]:
np.arange(0, 10, 3)

array([0, 3, 6, 9])

In [31]:
np.linspace(0,10,50)

array([  0.        ,   0.20408163,   0.40816327,   0.6122449 ,
         0.81632653,   1.02040816,   1.2244898 ,   1.42857143,
         1.63265306,   1.83673469,   2.04081633,   2.24489796,
         2.44897959,   2.65306122,   2.85714286,   3.06122449,
         3.26530612,   3.46938776,   3.67346939,   3.87755102,
         4.08163265,   4.28571429,   4.48979592,   4.69387755,
         4.89795918,   5.10204082,   5.30612245,   5.51020408,
         5.71428571,   5.91836735,   6.12244898,   6.32653061,
         6.53061224,   6.73469388,   6.93877551,   7.14285714,
         7.34693878,   7.55102041,   7.75510204,   7.95918367,
         8.16326531,   8.36734694,   8.57142857,   8.7755102 ,
         8.97959184,   9.18367347,   9.3877551 ,   9.59183673,
         9.79591837,  10.        ])

## eye

Creates an identity matrix

**Can numpy do inverses, RREF, or eignstuff?**

In [37]:
np.eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

## Random 

Numpy also has lots of ways to create random number arrays:

### rand
Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

In [31]:
np.random.rand(2)

array([0.192773  , 0.92619102])

In [34]:
np.random.rand(1)[0]

0.1751697121669873

In [35]:
np.random.rand(5,5)  # not a tuple, separate arguments

array([[0.95380431, 0.6883206 , 0.22152805, 0.71395176, 0.5438837 ],
       [0.19695892, 0.02688933, 0.8007119 , 0.86847052, 0.49279226],
       [0.98157856, 0.20815559, 0.80963945, 0.50038731, 0.47570003],
       [0.21560764, 0.66409939, 0.67653006, 0.73336199, 0.94682868],
       [0.42437961, 0.91055504, 0.63560901, 0.03884626, 0.62931685]])

In [37]:
rows = 2
columns = 3
np.random.rand(rows, columns)

array([[0.57274902, 0.8813211 , 0.60331213],
       [0.60487407, 0.64772565, 0.94057039]])

In [38]:
np.random.rand(*(rows, columns))

array([[0.78504992, 0.13336706, 0.15310044],
       [0.2442683 , 0.22292936, 0.94964976]])

### randn

Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

**You'll have to brush up on standard normal distributions, but it will come up later on when we start graphing**

In [48]:
np.random.randn(2)

array([-0.27954018,  0.90078368])

In [39]:
np.random.randn(5,5)

array([[ 0.69528141, -0.57287524,  0.58266377,  1.31411431,  0.76450646],
       [ 0.62717692, -0.53747893, -1.2498243 , -0.16088397,  0.09484014],
       [ 0.78591899, -1.36971257,  0.19990519,  0.25542641, -0.29230877],
       [ 0.71376081, -0.67159114, -0.28798968, -0.69493712,  1.61138305],
       [ 0.66700899, -0.92014014,  0.10384738, -0.79781568, -0.26681805]])

In [42]:
sorted(np.random.randn(5))

[-1.8798625514613934,
 -1.7032379030000784,
 -0.4436277445052436,
 -0.022889992383397152,
 0.2375314238135361]

### randint
Return random integers from `low` (inclusive) to `high` (exclusive).

In [43]:
np.random.randint(1,100)

25

In [45]:
int(np.random.rand(1) * 100)

62

In [46]:
np.random.randint(1,100,10)

array([27, 23, 76, 93, 97, 43, 63, 51, 68, 95])

In [48]:
np.random.randint(-50, 323, 17)

array([ 73, -28,  91, 139, 315, 184, 266, 240, 124, 127,  11, 200, 142,
       293, 162, 260,   3])

## Array Attributes and Methods

Let's discuss some useful attributes and methods or an array:

In [49]:
arr = np.arange(25)  # one dimensional array fro zero to 24
ranarr = np.random.randint(0,50,10)  # one dimensional array of random ints from zero to 50

In [50]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [51]:
ranarr

array([29, 45, 29, 37, 23, 44, 39, 15, 35, 29])

## Reshape
Returns an array containing the same data with a new shape.

In [52]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [61]:
np.arange(20).reshape(1, 20)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19]])

In [62]:
np.random.randint(0, 20, 20).reshape(20)

array([11,  1, 12,  8,  7, 17, 15, 12, 18,  0,  1,  8, 16, 15,  0, 14,  6,
       12, 12, 11])

In [63]:
# Doing a reshape of (1, length) will give a 2D array (one row one column), while doing a reshape of 
# (length) will give a 1D array

### max,min,argmax,argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [65]:
ranarr

array([29, 45, 29, 37, 23, 44, 39, 15, 35, 29])

In [66]:
ranarr.max()

45

In [67]:
ranarr.argmax()

1

In [70]:
ranarr[ranarr.argmax()] == ranarr.max()

True

In [68]:
ranarr.min()

15

In [71]:
ranarr.argmin()

7

In [73]:
ranarr[ranarr.argmin()] == ranarr.min()

True

In [82]:
a_matrix = np.random.randint(0, 20, 20).reshape(4, 5)
a_matrix

array([[ 2, 19,  8,  2, 13],
       [ 7,  7,  0, 11, 16],
       [ 9, 10, 10, 11,  7],
       [ 5, 18, 10,  6,  8]])

In [83]:
a_matrix.argmax()

1

In [84]:
a_matrix[a_matrix.argmax()]

array([ 7,  7,  0, 11, 16])

In [87]:
a_matrix.reshape(20)[a_matrix.argmax()]

19

In [88]:
# argmax will find the maximum value and return an index based on the flattend out array

In [95]:
# But you can also specify to find the index based on a certain axis of the array instead
# (for 2x2 matrices) Vertically down rows is known as axis 0 (i.e. columns) and 
# horizontally across columns is known as axis 1 (i.e. rows)

In [96]:
# Find the index of the max value in each column
a_matrix.argmax(axis=0)

array([2, 0, 2, 1, 1])

In [97]:
a_matrix.max(axis=0)

array([ 9, 19, 10, 11, 16])

In [99]:
# Now do the same but for each row instead
a_matrix.argmax(axis=1)

array([1, 4, 3, 1])

In [100]:
a_matrix.max(axis=1)

array([19, 16, 11, 18])

## Shape

Shape is an attribute that arrays have (not a method):

In [65]:
# Vector
arr.shape

(25,)

In [66]:
# Notice the two sets of brackets
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24]])

In [69]:
arr.reshape(1,25).shape

(1, 25)

In [70]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [101]:
arr.reshape(25,1).shape

(25, 1)

In [102]:
arr.reshape(5, 5).shape

(5, 5)

### dtype

You can also grab the data type of the object in the array:

In [103]:
arr.dtype

dtype('int64')

In [104]:
np.array(['list', 32]).dtype

dtype('<U4')

# Great Job!